name: Deploy AWS EC2
on:
  workflow_run:
    workflows: ['Build Maven']
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.head_branch == 'main'  # chỉ chạy khi nhánh main
    steps:
      - name: SSH to EC2 and deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            # Stop container if exist
            docker stop aws-spring-demo || true && 
            docker rm aws-spring-demo || true && 

            # Pull git
            cd aws-spring-demo && 
            git pull && 

            # Build docker image
            ./mvnw compile jib:dockerBuild && 

            # Run docker container
            docker run -d -p 80:8080 --name aws-spring-demo spring-demo
            '
